### PR TITLE
SChannelSettings: Property `WinHttpDefaultSecureProtocols` returns array

### LINKED ISSUE #27: Explicit define what function `Get-LocalizedData` to call
This module is using the module DscResource.Common that have the command `Get-LocalizedData`. But the module [SChannelDsc.Util](https://github.com/dsccommunity/SChannelDsc/tree/master/source/Modules/SChannelDsc.Util) also has `Get-LocalizedData`, so if `DscResource.Common` is imported into the session the wrong command might be called, failing the resource.

https://github.com/dsccommunity/SChannelDsc/blob/b029a1f4b7e7b96ed0f65dc4ee697a943b55df5b/build.yaml#L17-L22

### LINKED ISSUE #28: SChannelSettings: `Test-TargetResource` always fails if current state only defined one `WinHttpDefaultSecureProtocols`
### Problem description

The `Test-TargetResource` will always fail if the current state has only defined one `WinHttpDefaultSecureProtocols`, e.g. 'TLS1.2'. This is because Get-TargetResource does not return a string array for the property `WinHttpDefaultSecureProtocols` resulting in that `Test-TargetResource` compares the array `@('TLS1.2')` against  `@('T','L','S','1','.','2')`.

### Verbose logs

```text
Not available (debugged but forgot to save the logs)
```

### DSC configuration

```powershell
SChannelSettings 'ConfigureWinHTTPProtocols'
{
    IsSingleInstance              = 'Yes'
    WinHttpDefaultSecureProtocols = @('TLS1.2')
}
```

### Suggested solution

Convert the value:.

https://github.com/dsccommunity/SChannelDsc/blob/b029a1f4b7e7b96ed0f65dc4ee697a943b55df5b/source/DSCResources/MSFT_SChannelSettings/MSFT_SChannelSettings.psm1#L326

to an array
```
WinHttpDefaultSecureProtocols   = @($winhttpProtocols)
```

### Operating system the target node is running

```text
Windows Server 2022
```

### PowerShell version and build the target node is running

```text
WMF 5.1
```

### SChannelDsc version

```text
v1.3.0
```

### PR DESCRIPTION
**Pull request by johlju**
#### Pull Request (PR) description

- SChannelDsc
  - Explicitly use the correct version of the command `Get-LocalizedData`
    ([issue #27](https://github.com/dsccommunity/SChannelDsc/issues/27)).
- SChannelSettings
  - Now the resource imports the dependent module *DscResource.Common*.
  - Now the property `WinHttpDefaultSecureProtocols` always return an array
    even if only one value is set in the current state ([issue #28](https://github.com/dsccommunity/SChannelDsc/issues/28)).

#### This Pull Request (PR) fixes the following issues

- Fixes #27
- Fixes #28

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof and comment-based
      help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/schanneldsc/29)

### CODE REVIEW

**Comment by johlju** [comment]
@ykuijs when you have time, please review this change. I will send in another PR that update the pipeline.

**Review by ykuijs — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/schanneldsc/29#-:-N2GMgAT3X5-l3F8tifp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Review by ykuijs — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/schanneldsc/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Comment by ykuijs** [comment]
Great, no problem of course!

**Pull request merged**
